jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
                invalidate_session: false
            anonymous:    true

    access_control:
        - { path: ^/_wdt, roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/about, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/legal, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile/me*, role: ROLE_USER }
        - { path: ^/profile/*, role: ROLE_ADMIN }
        - { path: ^/user/*, role: ROLE_ADMIN }
# die folgende Regel muss am Ende stehen
        - { path: ^/*, role: IS_AUTHENTICATED_FULLY }
